### ISSUE TITLE
Weapon Enchants are broken in 10.1

### ISSUE THREAD

**Issue by RShadowhand** [Dicebar/Bufflehead#4]
I've made a patch that seems to be working:
In `Main.lua`, replace these two lines
```
if ttInfo.lines[i].args[2] then
  local text = ttInfo.lines[i].args[2].stringVal
```
with these:
```
if ttInfo.lines[i].leftText then
  local text = ttInfo.lines[i].leftText.stringVal
```

Line numbers 169 and 170.

**Comment by Dicebar** [comment]
Hey RShadowhand!

Thanks for the report and the patch. I pushed an update with the relevant fixes, and it should be available on CurseForge in a few minutes.
